"""Generate a PyInstaller version file for the packaged exe.

Writes ssd_temp_monitor_version.txt in the format PyInstaller's
--version-file expects (a Python literal of VSVersionInfo). The version
is kept in sync with APP_VERSION automatically at build time.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "ssd_temp_tray.py"
OUT = ROOT / "ssd_temp_monitor_version.txt"

BUILD_DATE = "2026-09-22"


def app_version():
    text = SRC.read_text(encoding="utf-8")
    m = re.search(r'^APP_VERSION\s*=\s*"([^"]+)"', text, re.M)
    if not m:
        raise SystemExit("APP_VERSION not found in ssd_temp_tray.py")
    return m.group(1)


def main():
    version = app_version()
    # FILEVERSION must be purely numeric: "1.9.0-rc1" -> (1, 9, 0, 0)
    core = version.split("-")[0]
    numbers = [int(x) for x in core.split(".")]
    while len(numbers) < 4:
        numbers.append(0)
    fv = tuple(numbers[:4])

    tmpl = '''# UTF-8
#
# PyInstaller version file for SSD Temperature Monitor ({version})
# Generated by make_version_file.py - do not edit by hand.
#
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={fv},
    prodvers={fv},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', 'SSD Temp Monitor Project'),
         StringStruct('FileDescription', 'SSD Temperature Tray Monitor for Windows'),
         StringStruct('FileVersion', '{version}'),
         StringStruct('InternalName', 'ssd_temp_monitor'),
         StringStruct('OriginalFilename', 'ssd_temp_monitor.exe'),
         StringStruct('ProductName', 'SSD Temperature Monitor'),
         StringStruct('ProductVersion', '{version}'),
         StringStruct('BuildDate', '{build_date}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
'''
    OUT.write_text(tmpl.format(fv=fv, version=version, build_date=BUILD_DATE),
                   encoding="utf-8")
    print(f"wrote {OUT.name} for version {version}")


if __name__ == "__main__":
    main()
